---
title: "03-16-4.terrain"
output: html_document
---

# Setup  
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(dplyr)
library(tidyr)
library(janitor)
library(readr)
library(sf) #vector manipulation
library(ggplot2)
library(viridis)
library(ggthemes)
library(gstat) #IDW
library(stars) #raster manipulation
library(terra) #topographical variables
library(patchwork) #combining multiple plots  
library(tibble) #rownames to column

```

```{r defining map theme}
mytheme_map <- 
  theme_map()+
  theme(legend.position = "right",
        panel.background = element_rect(fill="gray80",
                                        color=NA),
        plot.background = element_rect(fill="gray80",
                                       color=NA),
        legend.title = element_text(size=14),
        legend.text = element_text(size=12))

```

```{r reading elevation data}
elev <- read_csv("../data/Deer Run1 Elevation.csv")

elev
```

# Wrangling  
```{r elev_w}
elev_w <- elev %>%
  clean_names() %>%
  rename(elev_ft=elevation) %>%
  mutate(elev_m=elev_ft*0.3048) %>%
  dplyr::select(elev_m,
                longitude,
                latitude) %>%
  st_as_sf(coords = c("longitude", "latitude")) %>%
  st_set_crs(value = 4326) %>%
  st_transform(crs = 6345)

elev_w

summary(elev_w)
```
# EDA  
```{r elev_w map}
ggplot()+
  geom_sf(data = elev_w,
          aes(color=elev_m), size=.01)+
  scale_fill_gradient(low="black", high="white")+
  mytheme_map

```

# Grid  

```{r boundary_w}
boundary_w <- read_sf("../data/boundary/DR1_boundary.geojson") %>%
  st_transform(crs = 6345)

boundary_w
```

```{r grid_r}
# grid in vector format
grid_r <-  boundary_w %>%
  st_make_grid(cellsize = 10) %>%
  st_as_sf() %>%
  st_rasterize(dx=10, dy=10) %>%
  st_crop(boundary_w)

grid_r

ggplot()+
  geom_stars(data = grid_r)+
  mytheme_map

```

# Interpolation  
```{r idw_mod}
idw_mod <- gstat(formula = elev_m ~ 1,  
                 data = elev_w)

idw_mod
```

```{r idw_pred}
idw_pred <- predict(idw_mod, grid_r) 

idw_pred
```

```{r elev_map }
elev_map <- ggplot()+
  geom_stars(data = idw_pred)+
  geom_sf(data=boundary_w, fill=NA)+
  scale_fill_gradient(low="black", high="white")+
  labs(fill="Elev. (m)")+
  mytheme_map

elev_map
```

# Computing secondary variables  
## Slope  
```{r slope}
slope <- idw_pred %>%
  dplyr::select(elev_m=var1.pred) %>%
  # Transforming to SpatRast for slope computation  
  terra::rast() %>%
  terra::terrain("slope", unit="radians") %>%  
  # Transforming back into stars (so works with ggplot)
  st_as_stars() %>%
  st_set_crs(value =  6345) #%>%
  # Transforming to pct
  #mutate(pct=tan(values)*100) %>%
  #dplyr::select(pct)

slope
```


```{r slope map}
slope_map <- ggplot()+
  geom_stars(data = slope)+
  geom_sf(data=boundary_w, fill=NA)+
  scale_fill_gradient(low="black", high="white")+
  labs(fill="Slope\n(rad)")+
  mytheme_map

slope_map
```

## Aspect  
```{r aspect}
aspect <- idw_pred %>%
  dplyr::select(elev_m=var1.pred) %>%
  terra::rast() %>%
  terra::terrain("aspect", unit="radians") %>%  
  st_as_stars() %>%
  st_set_crs(value =  6345)

aspect
```


```{r aspect map}
aspect_map <- ggplot()+
  geom_stars(data = aspect)+
  geom_sf(data=boundary_w, fill=NA)+
  scale_fill_gradient(low="black", high="white")+
  labs(fill="Aspect\n(rad.)")+
  mytheme_map

aspect_map
```

## Flow direction  
```{r flowdir}
flowdir <- idw_pred %>%
  dplyr::select(elev_m=var1.pred) %>%
  terra::rast() %>%
  terra::terrain("flowdir", unit="radians") %>%  
  st_as_stars() %>%
  st_set_crs(value =  6345)

flowdir
```


```{r flowdir map}
flowdir_map <- ggplot()+
  geom_stars(data = flowdir)+
  geom_sf(data=boundary_w, fill=NA)+
  scale_fill_gradient(low="black", high="white")+
  labs(fill="Flow dir.\n(degree)")+
  mytheme_map

flowdir_map
```

```{r flowdir map 2}
ggplot()+
  geom_stars(data = flowdir %>%
               mutate(values=factor(values)))+
  geom_sf(data=boundary_w, fill=NA)+
  scale_fill_discrete()+
  labs(fill="Flow dir.\n(degree)")+
  mytheme_map+
  facet_wrap(~values)+
  theme(legend.position = "none")

```

```{r hill shade}
slope_spv <- slope %>%
  # Transforming from starts to raster to work with shade function
  as("Raster") %>%
  rast() 

aspect_spv <- aspect %>%
  as("Raster") %>%
  rast() 

hill <- shade(slope_spv, aspect_spv) %>%
  st_as_stars()

hillshade_map <- ggplot()+
  geom_stars(data=hill)+
  scale_fill_gradient(low="black", high="white")+
  geom_sf(data = boundary_w, fill=NA)+
  labs(fill="Hill\nshade")+
  mytheme_map

hillshade_map
```

## Plotting all together
```{r plotting all together}
elev_map + slope_map + aspect_map + flowdir_map + hillshade_map 

ggsave("../output/Rojas_terrain.png", width = 10, height = 6)
```


# Grid extraction  
```{r elev_v}
elev_v <- idw_pred %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(elev_m=var1.pred) 

elev_v
```


```{r slope_v}
slope_v <- slope %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(slope=values) 

slope_v
```


```{r aspect_v}
aspect_v <- aspect %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(aspect=values) 

aspect_v
```
```{r flowdir_v}
flowdir_v <- flowdir %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(flowdir=values) 

flowdir_v
```
```{r hillshade_v}
hillshade_v <- hill %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(hillshade=values) 

hillshade_v
```

# Merging all in topo variables in one object  

```{r terrain_v }
terrain_v <- elev_v %>%
  st_join(slope_v,
          join = st_equals, 
          left = T) %>%
  st_join(aspect_v,
          join = st_equals, 
          left = T) %>%
  st_join(flowdir_v,
          join = st_equals, 
          left = T) %>%
  st_join(hillshade_v,
          join = st_equals, 
          left = T)

terrain_v %>%
  summary()
```

# Exporting  
 
```{r exporting}
write_sf(terrain_v, "../data/Rojas_terrain_v.geojson",
         delete_dsn = T)
```



