 ---
title: "interpolation"
output: html_document
---


# Setup  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("gstat")
#install.packages("stars")
#install.packages("cubelyr")
#install.packages("raster")


# Packages
library(dplyr)
library(tidyr)
library(sf)
library(ggplot2)
library(viridis)
library(gstat)
library(raster)
library(stars)

```

```{r reading yield data}
yield16_c <- read_sf("../output/Rojas_Yield16_Clean.geojson")

yield16_c
```

```{r summary}
summary(yield16_c)
```


```{r boundary}
boundary_w <- read_sf("../data/boundary/DR1_boundary.geojson") %>%
  st_transform(crs = 6345)

boundary_w
```

# Interpolation  

```{r yield clean map}
yieldclean_map <- ggplot()+
  geom_sf(data = yield16_c,
          aes(color=yield_lbac), size=.1)+
  scale_color_viridis()+
  geom_sf(data = boundary_w,
          fill=NA,
          color="blue")

yieldclean_map
```

## Grid
```{r grid_v}
# grid in vector format
grid_v <- st_make_grid(boundary_w, 
                     cellsize = 10) 

grid_v

class(grid_v)
```

```{r grid vector plot}
yieldclean_map+
  geom_sf(data = grid_v, 
          alpha=.5,
          fill=NA,
          size=.1)
```



```{r grid_r}
# grid in raster format 
grid_r <- grid_v %>%
  st_as_sf() %>%
  st_rasterize(dx=5, dy=5) %>%
  st_crop(boundary_w)

grid_r

class(grid_r)
```

```{r grid_r plot}
yieldclean_map+
  geom_stars(data = grid_r, 
          alpha=.7)
```

## IDW  
    
```{r idw_mod}
idw_mod <- gstat(formula = yield_lbac ~ 1,  
                 data = yield16_c)

idw_mod

class(idw_mod)
```

 
```{r idw_pred}
idw_pred <- predict(idw_mod, grid_r)

idw_pred

class(idw_pred)
```

```{r idw_pred plot}
ggplot()+
  geom_stars(data = idw_pred)+
  scale_fill_viridis()+
  geom_sf(data = boundary_w,
          fill=NA)+
  geom_sf(data = grid_v, 
          alpha=.5,
          fill=NA,
          size=.1)

```

# Grid extraction  


```{r idw_pred_v}
idw_pred_v <- idw_pred %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  rename(ipyield_lbac=var1.pred)

idw_pred_v

class(idw_pred_v)
```

```{r idw_pred_v plot}
ggplot()+
  geom_sf(data = idw_pred_v,
          aes(color=ipyield_lbac))+
  scale_color_viridis()

```

```{r interpolated distribution}
idw_pred_v %>%
  ggplot(aes(x=ipyield_lbac))+
  geom_density()

```

# Exporting to file  
 

```{r exporting}
write_sf(idw_pred_v,
         "../output/Rojas_Yield16_Clean_ip.geojson",
         delete_dsn = T)
```



