---
title: "03-16_3.yieldstability"
output: html_document
---

# Setup  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(dplyr)
library(tidyr)
library(sf)
library(ggplot2)
library(viridis)
library(ggthemes)
library(tibble)
#install.packages("tibble")

```

```{r yieldic16}
yieldic16 <- read_sf("../output/Rojas_Yield16_Clean_ip.geojson")

yieldic16

summary(yieldic16)
```

# Spatial stability  

```{r s_16}
s_16 <- yieldic16 %>%
  mutate(medianyield_lbac=median(ipyield_lbac)) %>%
  mutate(snyield=case_when(
    ipyield_lbac >= medianyield_lbac ~ "high",
    ipyield_lbac < medianyield_lbac ~ "low"
  )) %>%
  dplyr::select(ipyield_lbac, snyield=snyield, geometry)

s_16
```

```{r s_16 map}
s_16_map <- ggplot()+
  geom_sf(data = s_16,
          aes(fill=snyield), color=NA)+
  scale_fill_viridis_d(option="E")+
  labs(title="2016")+
  theme_map()+
  theme(legend.position = "right")


s_16_map 
```

```{r save output map}
ggsave("../output/Rojas_Yield16_spatialstability.png",
       width = 7, height = 3.5)

```

```{r st_all}
st_all <- s_16 
st_all
```
```{r st_all_map}
ggplot()+
  geom_sf(data = st_all,
          aes(fill=snyield), color=NA)+
    scale_fill_viridis_d(option="C")+
  theme_map()

ggsave("../data/Rojas_yield_st_16-1.geojson",
       width = 6, height = 4)

```


```{r proportion per stability zone}
st_all %>%
  group_by(snyield) %>%
  tally() %>%
  mutate(prop=(n/4032)*100)

```


# Exporting  
  
```{r exporting yield stability}
write_sf(s_16, 
         "../data/Rojas_yield_st_16.geojson",
         delete_dsn = T)
```

 